version: "3"
services:
  server:
    build:
      context: server/
    ports:
      - "8000:8000"
    volumes:
      - .:/code
  client:
    build:
      context: client/
    tty: true
    ports:
      - "3000:3000"
