# Generated by Django 4.0.3 on 2022-04-07 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='therapy_sessions.session'),
        ),
    ]
