# Generated by Django 4.0.3 on 2022-04-07 20:32

from django.db import migrations

from therapy_sessions.tests.utils import patient_factory, therapist_factory


def seed_db(apps, schema_editor):
    Therapist = apps.get_model('therapy_sessions', 'Therapist')
    Patient = apps.get_model('therapy_sessions', 'Patient')

    patient_factory(model=Patient)
    patient_factory(model=Patient)
    patient_factory(model=Patient)
    patient_factory(model=Patient)
    therapist_factory(model=Therapist)


class Migration(migrations.Migration):

    dependencies = [
        ('therapy_sessions', '0002_alter_payment_session'),
    ]

    operations = [
        migrations.RunPython(seed_db),
    ]
